[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "labels-app"
version = "0.1.0"
description = "Two-page FastAPI app with Postgres and Alembic"
requires-python = ">=3.11"